export interface CommonResponse<T = any>{
    succcessOrNot: string;
    statusCode: string;
    data?: T;
}

export enum StatusCode {
    SUCCESS = 'SUCCESS',
    SESSION_EXPIRE = 'SESSION_EXPIRE',
    MANDATORY_PARAM_ERROR = 'MANDATORY_PARAM_ERROR',
    BAD_REQUEST_ERROR = 'BAD_REQUEST_ERROR',
    INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
    INCORRECT_USERNAME_OR_PASSWORD = 'INCORRECT_USERNAME_OR_PASSWORD',
    WITHDRAWAL = 'WITHDRAWAL',
    HALT = 'HALT',
    DORMANT = 'DORMANT',
    FORCED_WITHDRAWAL = 'FORCED_WITHDRAWAL',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    EXIST_DUPLICATION_EMAIL = 'EXIST_DUPLICATION_EMAIL',
    EXIST_DUPLICATION_NICKNAME = 'EXIST_DUPLICATION_NICKNAME',
    INVALID_NICKNAME = 'INVALID_NICKNAME ',
}